import { useEffect, useMemo, useState } from 'react';
import { api } from './api';
import './styles/sales-insights.css';

const downloadCsv = (name, rows) => { const csv = rows.map((row) => row.map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')).join('\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = name; link.click(); URL.revokeObjectURL(link.href); };

export default function SalesInsights({ products, toast }) {
  const [orders, setOrders] = useState([]), [range, setRange] = useState('all');
  const load = () => { api.orders().then((result) => setOrders(result.orders || [])).catch((err) => toast(err.message, 'error')); };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => { const days = range === 'week' ? 7 : range === 'month' ? 30 : 0; if (!days) return orders; const since = Date.now() - days * 86400000; return orders.filter((order) => new Date(order.createdAt).getTime() >= since); }, [orders, range]);
  const completed = visible.filter((order) => !['cancelled'].includes(order.status)); const revenue = completed.reduce((sum, order) => sum + Number(order.total || 0), 0); const pending = orders.filter((order) => order.status === 'new').length; const lowStock = products.filter((product) => Number(product.quantity) <= 5).length;
  const topProducts = useMemo(() => Object.values(completed.flatMap((order) => order.items || []).reduce((map, item) => { map[item.productId] ||= { title: item.title, quantity: 0, sales: 0 }; map[item.productId].quantity += Number(item.quantity); map[item.productId].sales += Number(item.price) * Number(item.quantity); return map; }, {})).sort((a, b) => b.sales - a.sales).slice(0, 4), [completed]);
  const exportOrders = () => downloadCsv('sim-orders.csv', [['Order', 'Date', 'Customer', 'Phone', 'Status', 'Total'], ...orders.map((order) => [order._id, new Date(order.createdAt).toLocaleString(), order.customer?.name, order.customer?.phone, order.status, order.total])]);
  const exportProducts = () => downloadCsv('sim-products.csv', [['Product', 'Category', 'Sell price', 'Cost', 'Stock', 'Discount %'], ...products.map((product) => [product.title, product.category, product.price, product.cost, product.quantity, product.discountPercent])]);
  return <section className="admin-section sales-insights mt-4"><div className="admin-section-title"><div><p className="eyebrow">LIVE BUSINESS INSIGHTS</p><h2>Sales <span>overview</span></h2></div><div className="insight-actions"><select value={range} onChange={(e) => setRange(e.target.value)}><option value="all">All time</option><option value="week">Last 7 days</option><option value="month">Last 30 days</option></select><button onClick={load}><i className="bi bi-arrow-clockwise"/></button></div></div><div className="sales-stats"><article><i className="bi bi-cash-stack"/><span>Sales revenue</span><strong>${revenue.toFixed(2)}</strong></article><article><i className="bi bi-bag-check"/><span>Orders</span><strong>{completed.length}</strong></article><article className={pending?'alert-card':''}><i className="bi bi-bell"/><span>New orders</span><strong>{pending}</strong></article><article className={lowStock?'alert-card':''}><i className="bi bi-box-seam"/><span>Low stock alerts</span><strong>{lowStock}</strong></article></div><div className="insight-bottom"><div><h3>Best-selling products</h3>{topProducts.length?<div className="top-products">{topProducts.map((item, index) => <p key={item.title}><b>0{index + 1}</b><span>{item.title}<small>{item.quantity} sold</small></span><strong>${item.sales.toFixed(2)}</strong></p>)}</div>:<p className="text-secondary">Complete orders to see your top products.</p>}</div><div className="export-panel"><i className="bi bi-file-earmark-spreadsheet"/><h3>Export your data</h3><p>Download a CSV file for Excel or Google Sheets.</p><button onClick={exportOrders}>Export orders</button><button onClick={exportProducts}>Export products</button></div></div></section>;
}
